# Generated by Django 3.0.8 on 2021-06-09 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('degree', models.CharField(blank=True, max_length=10, null=True)),
                ('cut', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sample_collected_at', models.CharField(choices=[('HOME', 'HOME'), ('LAB', 'LAB'), ('HOSPITAL', 'HOSPITAL'), ('OTHER', 'OTHER')], default='LAB', max_length=100)),
                ('sample_collection_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('investigation_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visiting_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('CARD', 'CARD'), ('OTHER', 'OTHER')], default='CASH', max_length=100)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('consulted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulted_by', to='lab.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENGER', 'TRANSGENGER'), ('UNDISCLOSED', 'UNDISCLOSED'), ('OTHER', 'OTHER')], default='MALE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('low_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('high_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('elabaorated_range', tinymce.models.HTMLField(blank=True, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResultThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=datetime.datetime.now)),
                ('results', models.CharField(default='NA', max_length=200)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Test')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('linked_test', models.ManyToManyField(to='lab.Test')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='investigation_package',
            field=models.ManyToManyField(blank=True, null=True, to='lab.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='investigation_test',
            field=models.ManyToManyField(blank=True, null=True, through='lab.ResultThrough', to='lab.Test'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Patient'),
        ),
        migrations.AddField(
            model_name='order',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='lab.Doctor'),
        ),
        migrations.CreateModel(
            name='LabInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LAB', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('checked', models.CharField(default='Checked By', max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_post', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('doctor_sign', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
