# Generated by Django 3.0.8 on 2021-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('low_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('high_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('elabaorated_range', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('linked_test', models.ManyToManyField(to='lab.Test')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
