# Generated by Django 3.0 on 2021-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
