# Generated by Django 3.0.8 on 2021-06-09 06:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_package_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='elabaorated_range',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
