# Generated by Django 3.0.8 on 2021-06-09 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20210609_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='prn',
            new_name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENGER', 'TRANSGENGER'), ('UNDISCLOSED', 'UNDISCLOSED'), ('OTHER', 'OTHER')], default='MALE', max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sample_collected_at', models.CharField(choices=[('HOME', 'HOME'), ('LAB', 'LAB'), ('HOSPITAL', 'HOSPITAL'), ('OTHER', 'OTHER')], default='LAB', max_length=100)),
                ('sample_collection_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('investigation_amount', models.CharField(max_length=20)),
                ('visiting_charge', models.CharField(max_length=20)),
                ('other_charge', models.CharField(max_length=20)),
                ('discount_amount', models.CharField(max_length=20)),
                ('final_amount', models.CharField(max_length=20)),
                ('advance_received', models.CharField(max_length=20)),
                ('balance_amount', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_notes', models.TextField()),
                ('consulted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulted_by', to='lab.Doctor')),
                ('investigation_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Package')),
                ('investigation_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Test')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Patient')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='lab.Doctor')),
            ],
        ),
    ]
