# Generated by Django 3.2.8 on 2022-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20210619_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referred_by',
            field=models.CharField(default='Dr. ', max_length=100),
        ),
    ]
