# Generated by Django 3.0.8 on 2021-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20210609_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='investigation_package',
        ),
        migrations.AddField(
            model_name='order',
            name='investigation_package',
            field=models.ManyToManyField(blank=True, null=True, to='lab.Package'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='investigation_test',
        ),
        migrations.AddField(
            model_name='order',
            name='investigation_test',
            field=models.ManyToManyField(blank=True, null=True, to='lab.Test'),
        ),
    ]
