# Generated by Django 3.0.8 on 2021-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20210609_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('CARD', 'CARD'), ('OTHER', 'OTHER')], default='CASH', max_length=100),
        ),
    ]
