# Generated by Django 3.0 on 2021-11-24 06:10

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20211124_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
