# Generated by Django 3.0 on 2021-11-24 07:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_patient_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='lft',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lab.Test'),
        ),
        migrations.AddField(
            model_name='test',
            name='rght',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
    ]
